---
- name: install epel
  yum:
    name:
      - epel-release
      - bind-utils
      - net-tools
      - ntp
      - firewalld
      - openssh-server
      - selinux-policy
    state: present
  become: true

- name: reload systemd
  systemd:
    daemon_reload: true
  become: true
