---
- name: set ntpd config
  template:
    src: "templates/ntp.conf.j2"
    dest: "/etc/ntp.conf"
    owner: root
    group: root
    mode: 0644
  become: true

- name: ensure SeLinux is enforcing
  selinux:
    policy: targeted
    state: enforcing
  become: true
