---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: centos/7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../playbook.yml
scenario:
  name: vagrant
verifier:
  name: testinfra
  directory: ../tests
  lint:
    name: flake8
