---

- name: place unbound.conf into place
  template:
    src: templates/unbound.conf.j2
    dest: /etc/unbound/unbound.conf
    owner: root
    group: unbound
    mode: 0644
  become: true

- name: copy remaining files
  template:
    src: "templates/{{ item }}"
    dest: /etc/unbound/conf.d/{{ item }}
    owner: root
    group: unbound
    mode: 0644
  with_items:
    - "malware.conf"
    - "rootzone.conf"
  become: true

- name: ensure log exists
  file:
    state: file
    path: "/var/log/unbound"
    owner: unbound
    group: unbound
    mode: 0644
  become: true

- name: ensure unbound is enabled
  service:
    name: unbound
    enabled: true
  notify:
    - start unbound
  become: true
